
// enter your API Gateway URL
@URL=https://<#####>.execute-api.<####>.amazonaws.com/prod/

POST {{URL}} HTTP/1.1
Content-Type: application/json
Accept: "application/json"

{
  "sourceLang": "en",
  "targetLang": "es",
  "text": "walk"
}